"""Admin API — customer management (read-heavy; mutations are rare).

Customer list excludes admin test sessions. When a business admin uses the
Agent Chat tester in the admin portal the request goes through /web/chat with
user_id="web-tester" (the stable admin test ID). That creates a CustomerChannel
row tagged Channel.WEB with external_user_id="web-tester". Because it is always
the same ID no new customer records accumulate, and the list endpoint filters
this known test identity so it does not appear alongside real customers from
WhatsApp, Telegram, or the customer-facing web chat embed.
"""

from __future__ import annotations

from sqlalchemy import func, or_, select

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_business, get_session
from app.models.business import Business
from app.models.customer import Customer, CustomerChannel
from app.models.enums import Channel
from app.repositories.customers import CustomerChannelRepository, CustomerRepository

router = APIRouter(prefix="/{slug}/customers", tags=["admin:customers"])

# External user IDs that identify admin/test sessions rather than real customers.
# "web-tester" is the stable ID used by the admin Agent Chat panel.
# "session-" prefixed IDs were generated by an earlier version of that panel.
_TEST_ID_EXACT = {"web-tester"}
_TEST_ID_PREFIX = "session-"


class CustomerOut(BaseModel):
    id: str
    name: str | None
    phone: str | None
    email: str | None

    @classmethod
    def from_orm(cls, c: Customer) -> "CustomerOut":
        return cls(
            id=str(c.id),
            name=c.name,
            phone=c.phone,
            email=c.email,
        )


@router.get("", response_model=list[CustomerOut])
async def list_customers(
    slug: str,
    limit: int = 50,
    offset: int = 0,
    business: Business = Depends(get_business),
    session: AsyncSession = Depends(get_session),
) -> list[CustomerOut]:
    """Return real customers — excludes admin Agent Chat test sessions.

    A customer is treated as a real customer when they have at least one
    non-WEB channel (WhatsApp / Telegram), OR when their web channel ID is not
    a known test identifier.  This keeps the list clean without touching any
    data — the test session record stays in the DB for conversation history.
    """
    # Subquery A: customer has at least one non-WEB channel → definitely real
    has_real_channel = (
        select(func.count(CustomerChannel.id))
        .where(CustomerChannel.business_id == business.id)
        .where(CustomerChannel.customer_id == Customer.id)
        .where(CustomerChannel.channel != Channel.WEB)
        .correlate(Customer)
        .scalar_subquery()
    )

    # Subquery B: customer has a WEB channel whose ID is not a test ID
    has_real_web_id = (
        select(func.count(CustomerChannel.id))
        .where(CustomerChannel.business_id == business.id)
        .where(CustomerChannel.customer_id == Customer.id)
        .where(CustomerChannel.channel == Channel.WEB)
        .where(CustomerChannel.external_user_id.notin_(_TEST_ID_EXACT))
        .where(~CustomerChannel.external_user_id.like(f"{_TEST_ID_PREFIX}%"))
        .correlate(Customer)
        .scalar_subquery()
    )

    stmt = (
        select(Customer)
        .where(Customer.business_id == business.id)
        .where(or_(has_real_channel > 0, has_real_web_id > 0))
        .order_by(Customer.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    result = await session.execute(stmt)
    return [CustomerOut.from_orm(c) for c in result.scalars().all()]


class ChannelOut(BaseModel):
    id: str
    channel: str
    external_user_id: str
    display_name: str | None


@router.get("/{customer_id}/channels", response_model=list[ChannelOut])
async def list_customer_channels(
    slug: str,
    customer_id: str,
    business: Business = Depends(get_business),
    session: AsyncSession = Depends(get_session),
) -> list[ChannelOut]:
    import uuid
    from app.core.errors import ValidationError
    try:
        cid = uuid.UUID(customer_id)
    except ValueError:
        raise ValidationError("customer_id must be a valid UUID.", details={"customer_id": customer_id})
    repo = CustomerChannelRepository(session, business.id)
    channels = await repo.list_for_customer(cid)
    return [
        ChannelOut(
            id=str(ch.id),
            channel=ch.channel.value,
            external_user_id=ch.external_user_id,
            display_name=ch.display_name,
        )
        for ch in channels
    ]


@router.get("/{customer_id}", response_model=CustomerOut)
async def get_customer(
    slug: str,
    customer_id: str,
    business: Business = Depends(get_business),
    session: AsyncSession = Depends(get_session),
) -> CustomerOut:
    import uuid
    from app.core.errors import ValidationError
    try:
        cid = uuid.UUID(customer_id)
    except ValueError:
        raise ValidationError("customer_id must be a valid UUID.", details={"customer_id": customer_id})
    repo = CustomerRepository(session, business.id)
    customer = await repo.get_or_raise(cid)
    return CustomerOut.from_orm(customer)
